### ISSUE TITLE
Add more content around DAG migration

### ISSUE THREAD

**Issue by ryw** [astronomerio/airflow-guides#15]
@andscoop commented on [Mon Jul 16 2018](https://github.com/astronomerio/astronomer-ee/pull/103)

**Comment by vparekh94** [comment]
@ryw for migrating from old cloud to new cloud (or 1.8 to 1.9), this is covered here:
https://github.com/astronomerio/airflow-guides/blob/master/guides/getting-started-with-new-cloud.md
