### ISSUE TITLE
Guide - Removing old DAGs from the UI

### ISSUE THREAD

**Issue by ryw** [astronomerio/airflow-guides#18]
@bonominijl commented on [Mon Jun 04 2018](https://github.com/astronomerio/astronomer-ee/issues/88)

Guide explaining the process for removing DAGs no longer in the dagbag but still present in postgres from an EE install with postgres access. 

---

@vparekh94 commented on [Mon Jun 11 2018](https://github.com/astronomerio/astronomer-ee/issues/88#issuecomment-396441199)

@bonominijl from  an old  prospect:

```
PGPASSWORD=$(kubectl get secret --namespace cmgdemo wintering-eel-postgresql -o jsonpath="{.data.postgres-password}" | base64 --decode; echo)

kubectl run --namespace cmgdemo wintering-eel-postgresql-client --restart=Never --rm --tty -i --image postgres \
   --env "PGPASSWORD=$PGPASSWORD" \
   --command -- psql -U postgres \
   -h wintering-eel-postgresql postgres
delete from xcom where dag_id = 'example_dag';
delete from task_instance where dag_id = 'example_dag';
delete from sla_miss where dag_id = 'example_dag';
delete from log where dag_id = 'example_dag';
delete from job where dag_id = 'example_dag';
delete from dag_run where dag_id = 'example_dag';
delete from dag where dag_id = 'example_dag';
```

---

@bonominijl commented on [Tue Jun 12 2018](https://github.com/astronomerio/astronomer-ee/issues/88#issuecomment-396631751)

@vparekh94 Awesome, thanks!

**Comment by vparekh94** [comment]
@ryw Airflow 1.10 comes with UI support for this - do you want to leave this open or rope it in with the 1.10 Astro release?

**Comment by ryw** [comment]
let's kill
