### ISSUE TITLE
Guide for setting Airflow version

### ISSUE THREAD

**Issue by ryw** [astronomerio/airflow-guides#22]
@schnie Can you type out here how to set Airflow version in 0.3,  and we can put it out as a guide?

**Comment by tedmiston** [comment]
I went on a docs rampage today and went ahead and took a crack at this one while I was in docs mode.  It will probably need some polish, but lmk what you think so far.

https://github.com/astronomerio/airflow-guides/pull/30

**Comment by gregbrunk** [comment]
@ryw - bump

**Comment by gregbrunk** [comment]
Also - if we have this guide, does it imply that https://app.zenhub.com/workspace/o/astronomerio/astronomer/issues/131 is now complete? Can I close it? @andscoop

**Comment by tedmiston** [comment]
Bumping the PR to try to get the guide I wrote a few weeks ago merged - https://github.com/astronomerio/airflow-guides/pull/30
