### ISSUE TITLE
KubernetesPodOperator Guide

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/airflow-guides#36]
We need a guide on the benefits + use of the `KubernetesPodOperator` once it's ready for 1.10

@rhwang10 wrote a description for a customer that we can generalize and throw in:

> Airflow 1.10 has more native Kubernetes support than 1.9 (current version). Previously, on 1.9, it was possible to use the DockerOperator if you wanted to run external tasks/code written in other languages, so in PSL’s case, you could spin up a docker container to easily import and run the Javascript web scraper wherever you needed it in your workflow. It wouldn’t be much effort to get this working in EE, but, it would play much more nicely if we were to spin up a new pod to manage that container instead of letting that container just exist on that cluster. You can imagine that a bunch of unmanaged containers running around could cause issues.
> 
> Using the KubernetesPodOperator accomplishes the same thing with minimal changes to your code (just have to specify a few k8s things like namespace). Rolling this out in an Airflow 1.10 release would be better than making it backwards compatible with 1.9, as it would be one less thing you have to manage.
> 

Relevant Issue: https://github.com/astronomerio/astronomer-ee/issues/116

**Comment by vparekh94** [comment]
The above guide outlines using it in an EE install - we should have info for using it in a cloud install soon.

**Comment by vparekh94** [comment]
This is taken care of here:
https://github.com/airflow-plugins/example_kubernetes_pod
