### ISSUE TITLE
subdags.md creating subdag wrong function call. 

### ISSUE THREAD

**Issue by kik-kik** [astronomerio/airflow-guides#48]
Function definition of a function returning a subdag:
```def load_subdag(parent_dag_name, child_dag_name, args):```

Later in the example when creating a subdag task a call is made to `extract_subdag()` instead of `load_subdag()`:

```load_tasks = SubDagOperator(
        task_id='load_tasks',
        subdag=extract_subdag('example_subdag_operator',
                           'load_tasks', default_args),
        default_args=default_args,
        dag=dag,
    )
```

**Comment by vparekh94** [comment]
thanks @kik-kik - just fixed. Deploying site now!
