### ISSUE TITLE
Clarify structure of project directory

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/airflow-guides#5]
Per @tedmiston's notes: "Plugins & DAGs should be structured under /plugins/<plugin_name> and /dags/<dag_name>"

**Comment by tedmiston** [comment]
lmk if you need anymore info from me on this

**Comment by vparekh94** [comment]
I think this is taken care of with:
https://github.com/astronomerio/astro-cli
https://github.com/astronomerio/airflow-guides/blob/master/guides/astro-cli.md

Closing for now
