### ISSUE TITLE
How does Airflow work with on-prem data sources?

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/airflow-guides#53]
Hey all- @ryw asked me to get info for a guide on this, as a customer inquired. Google doc for notes here:
https://docs.google.com/document/d/1JlIvOuzvcluFfhCHTL2Xh4LgE1RXvSOabvFX6gPloQM/edit

@ryw - this is the question you were referring to right?

**Comment by vparekh94** [comment]
This would be the same as connecting to any other data source - as long as there's some sort of endpoint available, we should be able to hit it (be it through FTP, HTTP, or whatever else).

**Comment by vparekh94** [comment]
@petedejoy can we close this out?

**Comment by vparekh94** [comment]
Closing for now
