### ISSUE TITLE
Airflow Generate Dynamically Created DAG based on Table Insertion in a Database

### ISSUE THREAD

**Issue by irvifa** [astronomerio/airflow-guides#55]
Hi,

I want to create a dynamically created DAG from database table query. When I'm trying to create a dynamically creating DAG from both of range of exact number or based on available object in airflow settings it's succeeded. However when I'm trying to use a PostgresHook and create a DAG for each of row of my table, I can see a new DAG generated whenever I add a new row in my table. However it turned out that I can't click the newly created DAG on my web server. I need your help.

Best,

**Comment by petedejoy** [comment]
@vparekh94 - mind scoping this and delegating content responsibility accordingly?

**Comment by irvifa** [comment]
Hi @petedejoy and @vparekh94 it seems like it's related to https://stackoverflow.com/questions/51218314/dags-not-clickable-on-google-cloud-composer-webserver-but-working-fine-on-a-loc/51386238#51386238 since I'm used cloud composer. Thank you guys, I'll close this issue for now.
