### ISSUE TITLE
Clarify CLI commands in Source-->Destination Guides

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/airflow-guides#6]
Per @tedmiston's notes: "It was unclear that they just had to $ astro airflow init and $ astro airflow up as opposed to pip install apache-airflow etc"

"They were doing an $ astro deploy every time even just for local testing instead of $ astro airflow down + $ astro airflow up"

**Comment by tedmiston** [comment]
lmk if you need anymore info from me on this

**Comment by vparekh94** [comment]
Covered in:

https://github.com/astronomerio/airflow-guides/blob/master/guides/astro-cli.md
https://github.com/astronomerio/astro-cli
