### ISSUE TITLE
Guide on using multiple Airflow environments

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/airflow-guides#61]
As a user, I'm migrating from my internal airflow set up to using  Astronomer Airflow. I'd love some guidance on when to use multiple Airflows, how that should work with local development, and guidance on setting each one up.

**Comment by vparekh94** [comment]
Dumping thoughts here from conversations today:

*General questions asked*:

_ How should code between different deployments be managed?_

_ How should code from one environment to another?_

_ How should we handle code that is mostly the same between different projects  (e.g. template DAGs)?

_We want each push to spin up a fresh environment


The answer I went with:
- it'll really depend on what the project looks like. Template code can be stored in a separate repo and imported as a module. As far as deployments go, we usually recommend 1 or 2 (prod, or staging and prod) deployments per repo, and then use a service account to figure out how that should flow together

.


@benjamingregory do you have anything to add here? How have you been doing it with your current engagement?

**Comment by Slater-Victoroff** [comment]
Running into this same question - wondering what a good flow for this is. A couple of specific flavors we're thinking about:

Is there a recommended structure for larger Airflow projects? For security reasons we can't really have everything in one DAGs directory and it would be a lot more convenient for us to instead have several different directories one per customer where we can just start up Airflow pointing at one of our DAG directories. Similarly we have to divvy up dags and tasks. Wondering if there's a best practice on where to put tasks, where to combine subdags - where to draw the line between a full dag and a sub dag etc... We can come up with thoughts around a lot of this, but wondering if there are any developing standards.

Runtime configuration: In most cases we want to change something at runtime (like the directory we're processing). Is the standard way of doing this just by editing your default args? Or is there a way of associating arbitrary kwargs with the DAG itself. The first is tenable but feels messy. The second is preferable if for no other reason than it keeps our namespace clear. Is there a best practice around this?

**Comment by vparekh94** [comment]
First draft of this here:
https://astronomer.io/guides/managing-airflow-code/

Closing this issue for now, please re open with anything additional that needs to be added
