### ISSUE TITLE
As an Astronomer Customer... guide

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/airflow-guides#62]
Let's try to make a guide with all onboarding information in one place to make the initial email less intimidating and drive traffic back to our site.

Let's try to get this up ASAP - tons of new cloud deals prospects coming in :)

**Comment by paolaperaza** [comment]
Just pushed up this guide: https://astronomer.io/guides/astro-customer-onboarding/

Will continue iterating with @vparekh94 @petedejoy but closing this out for now.
