### ISSUE TITLE
Add detail on task relationships in Dependencies guide

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/airflow-guides#70]
Direct feedback from a customer, whom at the time was looking for bet practices on inserting a manual step in a DAG:

> It might be handy to include documentation on the list/tuple syntax of task relationships (a >> (b, c) >> d) ... it's handy and the core documentation doesn't cover it AFAIK.

There's already a good bit in the existing [Managing Dependencies in Apache Airflow](https://www.astronomer.io/guides/managing-dependencies/), but it should be looked at and added to.

**Comment by vparekh94** [comment]
^ Added a quick example, should be enough for this
