### ISSUE TITLE
Add fix to pulling postgres error to CLI guide

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/airflow-guides#71]
Direct feedback from a customer who had installed our CLI, docker, Ubuntu 18 (they're running Windows): 

The problem (especially seen with users running WSL) - to be added to [this guide](https://www.astronomer.io/guides/install-cli-windows10-wsl/):  

> I'm pretty sure things are set up correctly - I can docker ps from ubuntu and see my windows containers.  I can astro workspace list and see my workspaces.  However when I try to call astro airflow start on my newly created workspace, I get the following error:

```
Sending build context to Docker daemon  8.192kB
Step 1/1 : FROM astronomerinc/ap-airflow:latest-onbuild
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> f28abf18b331
Successfully built f28abf18b331
Successfully tagged hello-astro/airflow:latest
INFO[0000] [0/3] [postgres]: Starting
Pulling postgres (postgres:10.1-alpine)...
panic: runtime error: index out of range
goroutine 52 [running]:
github.com/astronomerio/astro-cli/vendor/github.com/Nvveen/Gotty.readTermInfo(0xc4202e0760, 0x1e, 0x0, 0x0, 0x0)
....
```

**Comment by petedejoy** [comment]
@paolaperaza- be sure to make appropriate edits in the corresponding docs, as this guide will be deprecated soon!

**Comment by paolaperaza** [comment]
**Update**: Pushed up a fix last night (to both docs + guides), need to go into preview and make sure everything renders/is in the right spot. Will cut a release and paste link in here today.

**Comment by paolaperaza** [comment]
Changes all added and pushed to master, but it's been more than a few mins and they're not rendering on preview.

@petedejoy will slack you separately to see what's up hope I didn't break anything 😬

**Comment by paolaperaza** [comment]
FIXED - 

- [The Astronomer CLI on the Windows Subsystem for Linux
](https://www.astronomer.io/guides/install-cli-windows10-wsl/)

- [Getting Started with Astronomer Cloud](https://www.astronomer.io/guides/getting-started-with-new-cloud/)

Also fixed in docs.
