### ISSUE TITLE
Update GCP install guide

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/airflow-guides#75]
The GCP install guide install guide assumes use of stable postgres. It should be more clear what the difference steps are per backend postgres

**Comment by ryw** [comment]
@bonominijl you on this?

**Comment by bonominijl** [comment]
Updated: https://github.com/astronomerio/astronomer/blob/master/docs/ee-installation-postgres.md
and
https://github.com/astronomerio/astronomer/blob/master/docs/ee-installation-k8s-secrets.md

**Comment by ryw** [comment]
@vparekh94 can we close this?
