### ISSUE TITLE
Make Connection | Password Clearer

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/airflow-guides#9]
@benjamingregory had a call with Alejandro + Logan from Ares Sportswear on 7/11, and said they had some confusion that could be cleared up in the guide titled [Managing your Connections in Apache Airflow](https://www.astronomer.io/guides/connections/). 

Per a slack convo, he said:

> They were confused when you saved a connection that the password field was empty after they checked on it again
> 
> They thought it was clearing the password and that they would have to reset it everytime. In reality, airflow just encrypts the password and doesn’t show it again

**Comment by vparekh94** [comment]
@paolaperaza this is covered here:
https://github.com/astronomerio/airflow-guides/blob/master/guides/airflow-ui.md

Closing this issue for now - feel free to port anything over from the guide above to the Connections guide.

**Comment by paolaperaza** [comment]
@vparekh94 I'm gonna add a line or two to both the UI + connections guide to make it slightly more explicit. Re-opening it real quick.

**Comment by paolaperaza** [comment]
Oops, forgot to add my commit to this issue - [link here](https://github.com/astronomerio/airflow-guides/commit/0d81471933296fb094a01fe5e36c4ab8bdbe5eb2).

Added the following under the `Connections` section: 

> **Note**: When you save a connection, expect the password field to be empty the next time you return to it. That's just Airflow encrypting the password - it does not need to be reset. "
